#!/bin/bash
#BSUB -nnodes 1
#BSUB -W 10
#BSUB -P nro106
###BSUB -alloc_flags "smt4 nvme"
###-BSUB -J janA
#BSUB -q batch


source /gpfs/alpine/scratch/zladd/nro106/axonproj/miniconda3/bin/activate
conda activate /gpfs/alpine/scratch/zladd/nro106/axonproj/miniconda3/envs/dot_env


# load modules
module load gcc/7.4.0 
module load python
module load cuda/10.1.168 

cd /gpfs/alpine/scratch/zladd/nro106/axonproj/benchmarking/GPU_genetic_alg/python

#determine number of nodes and total procs
nprocspn=1
nnodes=$(cat ${LSB_DJOB_HOSTFILE} | sort | uniq | grep -v login | grep -v batch | wc -l)
nprocs=$(( ${nnodes} * ${nprocspn} ))
echo 'M: nprocs=',$nprocs

#run
cat ${LSB_DJOB_HOSTFILE} | sort | uniq | grep -v login | grep -v batch > host_list

echo "starting mascarpone" `date`
jsrun  -n ${nnodes} -g 6 -c 42 -a ${nprocspn} --bind=proportional-packed:7 --launch_distribution=packed stdbuf -o0  python optimize_parameters_genetic_alg.py --offspring_size 10 --max_ngen 1


echo "finished mascarpone" `date`

# attic --stdio_mode=prepended   
# attic2: jsrun xxx | & tee out.fp16.lag0.${LSB_JOBID}
